<?php

use Database\Seeders\DataMasterSeeder;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'id' => 1,
                'username' => 'hc',
                'name' => 'hc',
                'role' => '0',
                'active' => '1',
                'no_pegawai' => 'EMP001',
                'profile' => 'avatars/WwGcznmOaHiM0sCSQ5uhQuawlikQasNFwB9cCfRl.png',
                'email' => 'hc@gmail.com',
                'personel_number' => '12345678',
                'status_data' => null,
                'keterangan' => null,
                'posisi' => 'ff',
                'gender' => 'Laki-Laki',
                'tempat_lahir' => 'Subang',
                'tanggal_lahir' => '2024-10-16',
                'no_ktp' => '3213142801040001',
                'phone' => '082119072382',
                'agama' => 'insyaalah islam',
                'kawin' => 'belom dong',
                'tanggungan' => '0',
                'npwp' => '123',
                'alamat' => 'Kp Cibogo, RT.20/RW.5, Desa.Cibogo, Cibogo',
                'rt' => '20',
                'rw' => '05',
                'kelurahan' => 'cibogo',
                'kecamatan' => 'cibogo',
                'kota' => 'Subang',
                'provinsi' => 'Jawabarat',
                'kode_pos' => '41285',
                'email_verified_at' => '2024-09-26 19:23:06',
                'password' => Hash::make('12345'),
                'no_bpjs' => null,
                'no_bpjstk' => null,
                'lokasi_bpjs' => null,
                'terdaftar_bpjstk' => null,
                'status_pegawai' => null,
                'remember_token' => null,
                'created_at' => '2024-09-26 19:23:06',
                'updated_at' => '2024-12-22 01:40:33',
                'project_id' => null,
                'deleteing' => 0,
            ],
            [
                'id' => 3,
                'username' => 'kasieka',
                'name' => 'kasieka',
                'role' => '2',
                'active' => '1',
                'no_pegawai' => 'EMP003',
                'profile' => 'avatars/W2l2X8kve70GGxWgwZv3haC7dQZdPD8jbNHCMWAG.png',
                'email' => 'kasieka@gmail.com',
                'personel_number' => '53454',
                'status_data' => null,
                'keterangan' => null,
                'posisi' => 'kasieka',
                'gender' => 'Laki-Laki',
                'tempat_lahir' => 'Subang',
                'tanggal_lahir' => '2024-10-01',
                'no_ktp' => '3213142801040002',
                'phone' => '082119072382',
                'agama' => 'insyaalah islam',
                'kawin' => 'belom dong',
                'tanggungan' => '1',
                'npwp' => '235345',
                'alamat' => 'Kp Cibogo, RT.20/RW.5, Desa.Cibogo, Cibogo',
                'rt' => '21',
                'rw' => '21',
                'kelurahan' => 'nff',
                'kecamatan' => 'ngfhg',
                'kota' => 'Subang',
                'provinsi' => 'Jawabarat',
                'kode_pos' => '41285',
                'email_verified_at' => '2024-09-26 19:23:06',
                'password' => Hash::make('12345'),
                'no_bpjs' => '1234',
                'no_bpjstk' => '1234',
                'lokasi_bpjs' => '1234',
                'terdaftar_bpjstk' => 'ya',
                'status_pegawai' => null,
                'remember_token' => null,
                'created_at' => '2024-09-26 19:23:07',
                'updated_at' => '2024-12-21 05:22:00',
                'project_id' => null,
                'deleteing' => 0,
            ],
            [
                'id' => 4,
                'username' => 'manajerhc',
                'name' => 'Manajer Hc',
                'role' => '3',
                'active' => '1',
                'no_pegawai' => 'EMP004',
                'profile' => 'avatars/fSvizit39Jusy6edcRRcrBNYdxD8AWpZ1cKe4Qh7.png',
                'email' => 'manajerhc@example.com',
                'personel_number' => null,
                'status_data' => null,
                'keterangan' => null,
                'posisi' => 'manager hc',
                'gender' => null,
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'no_ktp' => null,
                'phone' => null,
                'agama' => null,
                'kawin' => null,
                'tanggungan' => null,
                'npwp' => null,
                'alamat' => null,
                'rt' => null,
                'rw' => null,
                'kelurahan' => null,
                'kecamatan' => null,
                'kota' => null,
                'provinsi' => null,
                'kode_pos' => null,
                'email_verified_at' => '2024-09-26 19:23:07',
                'password' => Hash::make('12345'),
                'no_bpjs' => null,
                'no_bpjstk' => null,
                'lokasi_bpjs' => null,
                'terdaftar_bpjstk' => null,
                'status_pegawai' => null,
                'remember_token' => null,
                'created_at' => '2024-09-26 19:23:07',
                'updated_at' => '2024-12-21 05:09:02',
                'project_id' => null,
                'deleteing' => 0,
            ],
        ]);
        $this->call([
            DataMasterSeeder::class,
        ]);
    }
}
